### ISSUE TITLE
README.md url for BML

### ISSUE THREAD

**Issue by bhourahine** [lanl/qmd-progress#109]
Current link in the document to https://qmmd.github.io/bml/ gives a  404 error.

Probably should either be pointing to https://qmmd.github.io/ or https://github.com/lanl/bml or something added at qmmd.github.io/bml/

**Comment by nicolasbock** [comment]
Thanks @bhourahine for reporting this! I have opened a PR (#111) which should address this issues. Please feel free to have a look at and review the PR. Thanks!
