### ISSUE TITLE
Compiling with graphlib and mpi in debug mode

### ISSUE THREAD

**Issue by cnegre** [lanl/qmd-progress#25]
The code compiles but gives a segfault due to the use of pointers to 
interface with metis. This occurs when trying to run /home/christian/qmd-progress/examples/gpmdcov
in debug mode.

**Comment by nicolasbock** [comment]
How do you build metis?

**Comment by nicolasbock** [comment]
metis-5.1.0
~~~
cd metis-5.1.0; make config; make
~~~

**Comment by nicolasbock** [comment]
When metis is built as a shared library we get a segfault. Building it as a static library things work.

**Comment by nicolasbock** [comment]
Seems like a bug in metis. Closing.
